services:
  redis:
    image: redis/redis-stack-server:6.2.6-v15
    container_name: filmer_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      filmer_network:


  cockroach:
    image: cockroachdb/cockroach:v24.3.5
    container_name: filmer_cockroach
    restart: always
    ports:
      - "8080:8080"
      - "26257:26257"
    volumes:
      - cockroach_data:/cockroach/cockroach-data:rw
    networks:
      filmer_network:
    command: "start-single-node --insecure"

  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: filmer_rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - ./rabbitmq/.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:rw
    networks:
      filmer_network:

networks:
  filmer_network:
    driver: bridge

volumes:
  cockroach_data:
  rabbitmq_data:
