services:
  redis:
    image: redis/redis-stack-server:6.2.6-v15
    container_name: filmer_redis
    restart: always
    expose:
      - "6379"
    networks:
      filmer_network:

  cockroach:
    image: cockroachdb/cockroach:v24.3.5
    container_name: filmer_cockroach
    volumes:
      - cockroach_data:/cockroach/cockroach-data:rw
    expose:
      - "26257"
    ports:
      - "8080:8080"
    networks:
      filmer_network:
    command: "start-single-node --insecure"
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: filmer_server
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - server_logs:/logs:rw
    ports:
      - "3000:3000"
    networks:
      filmer_network:
    depends_on:
      - cockroach
      - redis


networks:
  filmer_network:
    driver: bridge


volumes:
  cockroach_data:
  server_logs:
