services:
  redis:
    image: redis/redis-stack-server:6.2.6-v15
    container_name: filmer_redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis_data:/data:rw
    networks:
      main_network:
    command: redis-stack-server --save 60 1 --appendonly no --dir /data --dbfilename dump.rdb

  cockroach:
    image: cockroachdb/cockroach:v24.3.5
    container_name: filmer_cockroach
    restart: always
    ports:
      - "127.0.0.1:8881:8080"
    expose:
      - "26257"
    volumes:
      - cockroach_data:/cockroach/cockroach-data:rw
    networks:
      main_network:
    command: "start-single-node --insecure"

  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: filmer_rabbitmq
    restart: always
    ports:
      - "127.0.0.1:8883:15672"
    expose:
      - "5672"
    env_file:
      - ./rabbitmq/.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:rw
    networks:
      filmer_network:

  server:
    build:
      context: ./server
      dockerfile: ./build/Dockerfile
    container_name: filmer_server
    restart: always
    env_file:
      - ./server/.env
      - ./rabbitmq/.env
    expose:
      - "3000"
    volumes:
      - server_logs:/app/logs:rw
    networks:
      main_network:
    depends_on:
      - redis
      - cockroach
      - rabbitmq

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: filmer_client
    restart: always
    env_file:
      - ./client/.env
    expose:
      - "3001"
    volumes:
      - client_logs:/logs:rw
    networks:
      main_network:
    depends_on:
      - server

  admin:
    build:
      context: ./admin
      dockerfile: ./build/Dockerfile
    container_name: filmer_admin
    restart: always
    env_file:
      - ./admin/config/.env
    ports:
      - "127.0.0.1:8882:3002"
    networks:
      main_network:
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: filmer_nginx
    restart: always
    ports:
      - "127.0.0.1:8801:80"
    networks:
      main_network:
    depends_on:
      - client

networks:
  main_network:
    driver: bridge

volumes:
  redis_data:
  cockroach_data:
  rabbitmq_data:
  server_logs:
  client_logs:
