services:
  redis:
    image: redis/redis-stack-server:6.2.6-v15
    container_name: filmer_redis
    restart: always
    expose:
      - "6379"
    networks:
      main_network:

  cockroach:
    image: cockroachdb/cockroach:v24.3.5
    container_name: filmer_cockroach
    volumes:
      - cockroach_data:/cockroach/cockroach-data:rw
    expose:
      - "26257"
    ports:
      - "127.0.0.1:8881:8080"
    networks:
      main_network:
    command: "start-single-node --insecure"
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: filmer_server
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - server_logs:/logs:rw
    expose:
      - "3000"
    networks:
      main_network:
    depends_on:
      - cockroach
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: filmer_nginx
    restart: always
    ports:
      - "127.0.0.1:8801:80"
    networks:
      main_network:
    depends_on:
      - server


networks:
  main_network:
    driver: bridge


volumes:
  cockroach_data:
  server_logs:
