// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package app_user

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD71c410dDecodeServerAppUser(in *jlexer.Lexer, out *SignUpIn) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD71c410dEncodeServerAppUser(out *jwriter.Writer, in SignUpIn) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SignUpIn) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD71c410dEncodeServerAppUser(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SignUpIn) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD71c410dEncodeServerAppUser(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SignUpIn) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD71c410dDecodeServerAppUser(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SignUpIn) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD71c410dDecodeServerAppUser(l, v)
}
func easyjsonD71c410dDecodeServerAppUser1(in *jlexer.Lexer, out *LoginIn) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD71c410dEncodeServerAppUser1(out *jwriter.Writer, in LoginIn) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginIn) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD71c410dEncodeServerAppUser1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginIn) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD71c410dEncodeServerAppUser1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginIn) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD71c410dDecodeServerAppUser1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginIn) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD71c410dDecodeServerAppUser1(l, v)
}
