// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8e1dc130DecodeFilmerServerInternalAppUserDeliveryHttp(in *jlexer.Lexer, out *changePasswordIn) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "currentPassword":
			out.CurrentPassword = string(in.String())
		case "newPassword":
			out.NewPassword = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8e1dc130EncodeFilmerServerInternalAppUserDeliveryHttp(out *jwriter.Writer, in changePasswordIn) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"currentPassword\":"
		out.RawString(prefix[1:])
		out.String(string(in.CurrentPassword))
	}
	{
		const prefix string = ",\"newPassword\":"
		out.RawString(prefix)
		out.String(string(in.NewPassword))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v changePasswordIn) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8e1dc130EncodeFilmerServerInternalAppUserDeliveryHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v changePasswordIn) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8e1dc130EncodeFilmerServerInternalAppUserDeliveryHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *changePasswordIn) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8e1dc130DecodeFilmerServerInternalAppUserDeliveryHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *changePasswordIn) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8e1dc130DecodeFilmerServerInternalAppUserDeliveryHttp(l, v)
}
