// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package kinopoisk_api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9e2e77eaDecodeServerKinopoiskApi(in *jlexer.Lexer, out *kinopoiskApiError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi(out *jwriter.Writer, in kinopoiskApiError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v kinopoiskApiError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v kinopoiskApiError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *kinopoiskApiError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *kinopoiskApiError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi1(in *jlexer.Lexer, out *SearchedFilms) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "docs":
			if in.IsNull() {
				in.Skip()
				out.Films = nil
			} else {
				in.Delim('[')
				if out.Films == nil {
					if !in.IsDelim(']') {
						out.Films = make([]Film, 0, 0)
					} else {
						out.Films = []Film{}
					}
				} else {
					out.Films = (out.Films)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Film
					(v1).UnmarshalEasyJSON(in)
					out.Films = append(out.Films, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			out.Total = int(in.Int())
		case "page":
			out.Page = int(in.Int())
		case "pages":
			out.Pages = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi1(out *jwriter.Writer, in SearchedFilms) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"docs\":"
		out.RawString(prefix[1:])
		if in.Films == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Films {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"page\":"
		out.RawString(prefix)
		out.Int(int(in.Page))
	}
	{
		const prefix string = ",\"pages\":"
		out.RawString(prefix)
		out.Int(int(in.Pages))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SearchedFilms) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SearchedFilms) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SearchedFilms) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SearchedFilms) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi1(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi2(in *jlexer.Lexer, out *RawFilmStaffSlice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(RawFilmStaffSlice, 0, 0)
			} else {
				*out = RawFilmStaffSlice{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v4 RawFilmStaff
			(v4).UnmarshalEasyJSON(in)
			*out = append(*out, v4)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi2(out *jwriter.Writer, in RawFilmStaffSlice) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in {
			if v5 > 0 {
				out.RawByte(',')
			}
			(v6).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v RawFilmStaffSlice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawFilmStaffSlice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawFilmStaffSlice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawFilmStaffSlice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi2(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi3(in *jlexer.Lexer, out *RawFilmStaff) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "staffId":
			out.StaffID = int(in.Int())
		case "nameRu":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "professionKey":
			out.ProfessionKey = string(in.String())
		case "posterUrl":
			out.ImgUrl = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi3(out *jwriter.Writer, in RawFilmStaff) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"staffId\":"
		out.RawString(prefix[1:])
		out.Int(int(in.StaffID))
	}
	{
		const prefix string = ",\"nameRu\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"professionKey\":"
		out.RawString(prefix)
		out.String(string(in.ProfessionKey))
	}
	{
		const prefix string = ",\"posterUrl\":"
		out.RawString(prefix)
		out.String(string(in.ImgUrl))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RawFilmStaff) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawFilmStaff) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawFilmStaff) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawFilmStaff) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi3(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi4(in *jlexer.Lexer, out *RawFilmInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "kinopoiskId":
			out.KinopoiskID = int(in.Int())
		case "nameRu":
			out.Title = string(in.String())
		case "ratingKinopoisk":
			out.RatingKinopoisk = float64(in.Float64())
		case "webUrl":
			out.WebUrl = string(in.String())
		case "year":
			out.Year = int(in.Int())
		case "filmLength":
			out.FilmLenMinutes = int(in.Int())
		case "description":
			out.Description = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "genres":
			if in.IsNull() {
				in.Skip()
				out.Genres = nil
			} else {
				in.Delim('[')
				if out.Genres == nil {
					if !in.IsDelim(']') {
						out.Genres = make([]GenreUnofficial, 0, 4)
					} else {
						out.Genres = []GenreUnofficial{}
					}
				} else {
					out.Genres = (out.Genres)[:0]
				}
				for !in.IsDelim(']') {
					var v7 GenreUnofficial
					(v7).UnmarshalEasyJSON(in)
					out.Genres = append(out.Genres, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi4(out *jwriter.Writer, in RawFilmInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"kinopoiskId\":"
		out.RawString(prefix[1:])
		out.Int(int(in.KinopoiskID))
	}
	{
		const prefix string = ",\"nameRu\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"ratingKinopoisk\":"
		out.RawString(prefix)
		out.Float64(float64(in.RatingKinopoisk))
	}
	{
		const prefix string = ",\"webUrl\":"
		out.RawString(prefix)
		out.String(string(in.WebUrl))
	}
	{
		const prefix string = ",\"year\":"
		out.RawString(prefix)
		out.Int(int(in.Year))
	}
	{
		const prefix string = ",\"filmLength\":"
		out.RawString(prefix)
		out.Int(int(in.FilmLenMinutes))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"genres\":"
		out.RawString(prefix)
		if in.Genres == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Genres {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RawFilmInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawFilmInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawFilmInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawFilmInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi4(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi5(in *jlexer.Lexer, out *Rating) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "kp":
			out.Kinopoisk = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi5(out *jwriter.Writer, in Rating) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"kp\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Kinopoisk))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Rating) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Rating) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Rating) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Rating) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi5(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi6(in *jlexer.Lexer, out *Poster) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi6(out *jwriter.Writer, in Poster) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Poster) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Poster) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Poster) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Poster) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi6(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi7(in *jlexer.Lexer, out *Person) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "role":
			if in.IsNull() {
				in.Skip()
				out.Role = nil
			} else {
				if out.Role == nil {
					out.Role = new(string)
				}
				*out.Role = string(in.String())
			}
		case "imgUrl":
			out.ImgUrl = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi7(out *jwriter.Writer, in Person) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		if in.Role == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Role))
		}
	}
	{
		const prefix string = ",\"imgUrl\":"
		out.RawString(prefix)
		out.String(string(in.ImgUrl))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Person) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Person) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Person) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Person) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi7(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi8(in *jlexer.Lexer, out *GenreUnofficial) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "genre":
			out.Genre = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi8(out *jwriter.Writer, in GenreUnofficial) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"genre\":"
		out.RawString(prefix[1:])
		out.String(string(in.Genre))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GenreUnofficial) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GenreUnofficial) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GenreUnofficial) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GenreUnofficial) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi8(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi9(in *jlexer.Lexer, out *Genre) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Genre = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi9(out *jwriter.Writer, in Genre) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Genre))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Genre) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Genre) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Genre) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Genre) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi9(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi10(in *jlexer.Lexer, out *FilmStaff) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "directors":
			if in.IsNull() {
				in.Skip()
				out.Directors = nil
			} else {
				in.Delim('[')
				if out.Directors == nil {
					if !in.IsDelim(']') {
						out.Directors = make([]Person, 0, 1)
					} else {
						out.Directors = []Person{}
					}
				} else {
					out.Directors = (out.Directors)[:0]
				}
				for !in.IsDelim(']') {
					var v10 Person
					(v10).UnmarshalEasyJSON(in)
					out.Directors = append(out.Directors, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "actors":
			if in.IsNull() {
				in.Skip()
				out.Actors = nil
			} else {
				in.Delim('[')
				if out.Actors == nil {
					if !in.IsDelim(']') {
						out.Actors = make([]Person, 0, 1)
					} else {
						out.Actors = []Person{}
					}
				} else {
					out.Actors = (out.Actors)[:0]
				}
				for !in.IsDelim(']') {
					var v11 Person
					(v11).UnmarshalEasyJSON(in)
					out.Actors = append(out.Actors, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi10(out *jwriter.Writer, in FilmStaff) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"directors\":"
		out.RawString(prefix[1:])
		if in.Directors == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.Directors {
				if v12 > 0 {
					out.RawByte(',')
				}
				(v13).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"actors\":"
		out.RawString(prefix)
		if in.Actors == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Actors {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FilmStaff) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FilmStaff) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FilmStaff) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FilmStaff) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi10(l, v)
}
func easyjson9e2e77eaDecodeServerKinopoiskApi11(in *jlexer.Lexer, out *Film) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Title = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "year":
			out.Year = int(in.Int())
		case "genres":
			if in.IsNull() {
				in.Skip()
				out.Genres = nil
			} else {
				in.Delim('[')
				if out.Genres == nil {
					if !in.IsDelim(']') {
						out.Genres = make([]Genre, 0, 4)
					} else {
						out.Genres = []Genre{}
					}
				} else {
					out.Genres = (out.Genres)[:0]
				}
				for !in.IsDelim(']') {
					var v16 Genre
					(v16).UnmarshalEasyJSON(in)
					out.Genres = append(out.Genres, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "poster":
			(out.Poster).UnmarshalEasyJSON(in)
		case "rating":
			(out.Rating).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e2e77eaEncodeServerKinopoiskApi11(out *jwriter.Writer, in Film) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"year\":"
		out.RawString(prefix)
		out.Int(int(in.Year))
	}
	{
		const prefix string = ",\"genres\":"
		out.RawString(prefix)
		if in.Genres == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Genres {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"poster\":"
		out.RawString(prefix)
		(in.Poster).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		(in.Rating).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Film) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e2e77eaEncodeServerKinopoiskApi11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Film) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e2e77eaEncodeServerKinopoiskApi11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Film) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e2e77eaDecodeServerKinopoiskApi11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Film) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e2e77eaDecodeServerKinopoiskApi11(l, v)
}
